### ISSUE TITLE
Nothing is printed when output is redirected to a file

### ISSUE THREAD

**Issue by igrapp** [mountassir/sspender#7]
Scenario:
Given on Ubuntu 19.10
And logged in into bash 
When "./sspender sspender.cgf 2>&1  1>sspender.log & " is executed
 and "cat sspended.log"
Then no output presented

Technical Notes: "cout << .... << "\n" should be replaced woth   "cout << .... << std::endl;
this will flush file and output will appear.

**Comment by mountassir** [comment]
endl was removed in [Commit](https://github.com/mountassir/sspender/commit/2b307c5a5a87134b8841a849e7dba50b78c5528b) for some reason.
