### ISSUE TITLE
List of disk devices

### ISSUE THREAD

**Issue by Flo-63** [mountassir/sspender#9]
Hi,

I'd like to include more than one disk drive in config. Unfortunatly, a comma separated list does not work:
name: "sda", "sdb", "sdc",
or
name: "sda, sdb, sdc",
is ignored. What is the right way to configure more than one disk?

Thx

Flo

**Comment by mountassir** [comment]
Hi, the sample config file has an example of how to add multiple disks [sspender.cfg](https://github.com/mountassir/sspender/blob/master/sspender.cfg#L31) 

Basically your config needs to have an entry for each disk, something like:
>      ...
>      disks = 
>      (
>			{
>				name: "sda",                  
>				no_suspend_if_not_idle: true, 
>				spind_down_if_idle: false,     
>				idle_load_threshold: 5,        
>				idle_time_threshold: 1        
>			},
>			{
>				name: "sdb",                   
>				no_suspend_if_not_idle: true, 
>				spind_down_if_idle: false,     
>				idle_load_threshold: 5,       
>				idle_time_threshold: 1       
>			}
>      );
>      ...

**Comment by mountassir** [comment]
Alternatively, and assuming you want to add all the drives attached to your machine, you can just enable the `all_disks` flag [here](https://github.com/mountassir/sspender/blob/master/sspender.cfg#L21).
